// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAVu8Ymh4fH2iYD8PEOZaxhABS59mTSoM',
    appId: '1:277846890101:web:f3c6856e712af679e50a3c',
    messagingSenderId: '277846890101',
    projectId: 'flutterpushnotifications-ca33d',
    authDomain: 'flutterpushnotifications-ca33d.firebaseapp.com',
    storageBucket: 'flutterpushnotifications-ca33d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYWi1YWbJEa1DdPkUZYiU6FEst3vNsBko',
    appId: '1:277846890101:android:5f5443acd08e6f1fe50a3c',
    messagingSenderId: '277846890101',
    projectId: 'flutterpushnotifications-ca33d',
    storageBucket: 'flutterpushnotifications-ca33d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY7tFB1JHRF5aColkEpYI4xk3WKGEuAf4',
    appId: '1:277846890101:ios:b5deba011524a8f3e50a3c',
    messagingSenderId: '277846890101',
    projectId: 'flutterpushnotifications-ca33d',
    storageBucket: 'flutterpushnotifications-ca33d.appspot.com',
    iosClientId: '277846890101-cmmkb4e8e8vovcdbittt2i1827d377a5.apps.googleusercontent.com',
    iosBundleId: 'com.flerma.examplePushNotifications',
  );
}
